name: build msyh
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        echo "/github/home/.local/bin" >> $GITHUB_PATH
        echo "/github/home/.deno/bin" >> $GITHUB_PATH
        pacman -Syu --noconfirm git fontforge curl p7zip jq python-pip unzip
        pip3 install --user afdko
        curl -fsSL https://deno.land/install.sh | sh
        realpath ~/.deno/bin/deno
        ~/.deno/bin/deno help
    - uses: actions/checkout@v3
    - name: download_sans
      run: deno run --config ./deno.json --allow-all --v8-flags=--max-old-space-size=8192 download_sans.ts
    - name: prepare
      run: |
        mkdir out
    - name: yahei.js
      run: |
        deno run --config ./deno.json --allow-all --v8-flags=--max-old-space-size=8192 yahei.js
        ls out/*
    - name: simsun.ts
      run: |
        deno run --config ./deno.json --allow-all --v8-flags=--max-old-space-size=8192 simsun.ts
        ls out/*
    - name: droid-sans-mono.ts
      run: |
        deno run --config ./deno.json --allow-all --v8-flags=--max-old-space-size=8192 droid-sans-mono.ts
        ls out/*
    - name: Compress font
      run: |
        cd out
        7z a ../YaHei.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: YaHei
        path: YaHei.zip
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        body: ""
        tag: "YAHEI-${{env.SANS_VERSION}}-UI-${{env.SANS_UI_VERSION}}-S-${{env.SERIF_VERSION}}"
        artifacts: YaHei.zip
        allowUpdates: true
