name: build msyh
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        echo "/github/home/.local/bin" >> $GITHUB_PATH
        echo "/github/home/.deno/bin" >> $GITHUB_PATH
        pacman -Syu --noconfirm git curl p7zip unzip tree python
        curl -fsSL https://deno.land/install.sh | sh
        realpath ~/.deno/bin/deno
        ~/.deno/bin/deno help
    - uses: actions/checkout@v3
    - name: Download Tools
      run: deno run --allow-all --v8-flags=--max-old-space-size=8192 download_tools.ts
    - name: Download fonts
      run: deno run --allow-all --v8-flags=--max-old-space-size=8192 download_fonts.ts
    - name: Prepare
      run: |
        pwd
        tree
        mkdir out
    - name: Process
      run: |
        deno run --allow-all --v8-flags=--max-old-space-size=8192 process.ts
        ls out
    - name: Compress font
      run: |
        cd out
        7z a ../YaHei.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: YaHei
        path: YaHei.zip
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        body: ""
        tag: "YAHEI-${{env.SANS_VERSION}}-UI-${{env.SANS_UI_VERSION}}-S-${{env.SERIF_VERSION}}"
        artifacts: YaHei.zip
        allowUpdates: true
