name: build msyh
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Install dependencies
      run: pacman -Syu --noconfirm git fontforge curl p7zip jq
    - uses: actions/checkout@v2
    - name: Grab latest version
      run: |
        curl -L https://api.github.com/repos/be5invis/Sarasa-Gothic/releases/latest -o api.json
        UPSTREAM_VERSION=$(cat api.json | jq -r .tag_name)
        DOWNLOAD_URL=$(cat api.json | jq -r '.assets[] | select(.name | test("sarasa-gothic-ttc-(?!unhinted)")) | .browser_download_url')
        echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> $GITHUB_ENV
        echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV
    - name: Download font
      run: curl -Lvo /tmp/ttc.7z $DOWNLOAD_URL
    - name: Extract font
      run: 7z x -odata /tmp/ttc.7z
    - name: Run script
      run: |
        mkdir out
        python3 extract.py
    - name: Compress font
      run: |
        cd out
        7z a ../out.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out
    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "upstream-${{ env.UPSTREAM_VERSION }}"
        prerelease: true
        title: Nightly build
        files: out.zip
