name: build msyh
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        echo "/github/home/.local/bin" >> $GITHUB_PATH
        echo "/github/home/.deno/bin" >> $GITHUB_PATH
        pacman -Syu --noconfirm git fontforge curl p7zip jq python-pip unzip
        pip3 install --user afdko
        curl -fsSL https://deno.land/install.sh | sh
        realpath ~/.deno/bin/deno
        ~/.deno/bin/deno help
    - uses: actions/checkout@v2
    - name: Grab latest version
      run: |
        git clone --depth=1 https://github.com/GuiWonder/SourceHanToClassic.git
        cd SourceHanToClassic
        TOOL_VERSION=`git rev-parse --short HEAD`
        cd ..
        echo "TOOL_VERSION=$TOOL_VERSION" >> $GITHUB_ENV
    - name: permission
      run: |
        chmod +x 0*.sh
    - name: download
      run: |
        ./01_download_fonts.sh
    - name: to_classic
      run: |
        ./02_to_classic.sh
    - name: Compress font
      run: |
        cd out
        7z a ../Advocate-Ancient.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Advocate Ancient
        path: Advocate-Ancient.zip
    - name: Copy font
      run: | 
        mkdir data
        cp out/SourceHanSans-*.otf data
        ls data/
        mkdir serif
        cp out/SourceHanSerif-Regular.otf serif
        rm -rf out
    - name: Run script
      run: |
        mkdir out
        echo "----------------------"
        deno run --allow-all --v8-flags=--max-old-space-size=8192 yahei.js
        echo "----------------------"
        deno run --allow-all --v8-flags=--max-old-space-size=8192 simsun.ts
        echo "----------------------"
        ls out/*
    - name: Compress font
      run: |
        cd out
        7z a ../YaHei.zip *
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: YaHei
        path: YaHei.zip
    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "SourceHanToClassic-${{env.TOOL_VERSION}}"
        prerelease: true
        title: Nightly build
        files: |
            YaHei.zip
            Advocate-Ancient.zip
