name: build msyh
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - name: Install dependencies
      run: pacman -Syu git fontforge wget p7zip
    - uses: actions/checkout@v2
    - name: Download font
      run: wget -O /tmp/ttc.7z  https://github.com/be5invis/Sarasa-Gothic/releases/download/v0.32.11/sarasa-gothic-ttc-0.32.11.7z
    - name: Extract font
      run: 7z x -odata /tmp/ttc.7z
    - name: Run script
      run: |
        mkdir out
        python3 extract.py
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: out
        path: out
